### ISSUE TITLE
Preact template is missing some config

### ISSUE THREAD

**Issue by zgoda** [PepsRyuu/create-nollup-app#1]
Fragment shorthand syntax (`<>...</>`) is not configured and results in `Uncaught ReferenceError: React is not defined`.

![Zrzut ekranu z 2021-05-11 22-07-17](https://user-images.githubusercontent.com/141999/117877836-588e4980-b2a5-11eb-9ca3-d56b95ae4887.png)

Using normal syntax (`<Fragment>...</Fragment>`) works fine.

**Comment by zgoda** [comment]
This may come from the fact that `babel-preset-preact` configures only `h` JSX pragma in `@babel/plugin-transform-react-jsx` and skips pragma for fragments. I may prepare a PR if you don't mind dropping dependency on `babel-preset-preact` and using bare Babel JSX transform plugin (BTW [this is what `preact-cli` does](https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/babel-config.js#L33)).

**Comment by PepsRyuu** [comment]
Seems like a reasonable solution! Happy to accept a PR on this one!

**Comment by PepsRyuu** [comment]
Much appreciated! Released in ```0.0.8```. :)
