### ISSUE TITLE
deprecated packages in react template

### ISSUE THREAD

**Issue by danielzzz** [PepsRyuu/create-nollup-app#4]
warning rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
warning rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
warning rollup-plugin-replace@2.2.0: This module has moved and is now available at @rollup/plugin-replace. Please update your dependencies. This version is no longer maintained.

**Comment by PepsRyuu** [comment]
Noted! Need to do a general update of all of the packages I think anyways!

**Comment by PepsRyuu** [comment]
Updated all packages in version ```0.0.9```.
